---
platform: linux
image_resource: {type: docker-image, source: {repository: pivotalgreenhouse/ci}}

inputs:
- name: ci
- name: cf-deployment

outputs:
- name: stemcell

run:
  path: ci/tasks/get-gcp-linux-stemcell/run

params:
  bosh_manifest_path: cf-deployment/cf-deployment.yml
