---
platform: linux

image_resource: {type: docker-image, source: {repository: pivotalgreenhouse/ci}}

inputs:
  - name: diego-windows-release
  - name: garden-windows-msi-file
  - name: garden-windows-setup-file
  - name: greenhouse-ci
  - name: diego-windows-msi-file
  - name: greenhouse-install-script-generator-file
  - name: hakim

run:
  path: greenhouse-ci/scripts/release.rb

params:
  GITHUB_TOKEN:

