---
platform: linux

image_resource: {type: docker-image, source: {repository: pivotalgreenhouse/ci}}

params:
  BOSH_TARGET: ~
  BOSH_USER: ~
  BOSH_PASSWORD: ~
  DEPLOYMENT_NAME: ~

run:
  path: bash
  args:
  - -c
  - "bosh -n -t ${BOSH_TARGET} delete deployment ${DEPLOYMENT_NAME}"
