---
platform: linux

image_resource: {type: docker-image, source: {repository: pivotalgreenhouse/ci}}

inputs:
  - name: diego-windows-msi-file
  - name: garden-windows-msi-file
  - name: diego-windows-cloudformation-template-file
  - name: garden-windows-setup-file
  - name: greenhouse-install-script-generator-file
  - name: greenhouse-ci
  - name: hakim

run:
  path: greenhouse-ci/scripts/deploy_msi.rb
  args: [msi-file]

params:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  BOSH_HOST:
  BOSH_PASSWORD:
  BOSH_USER:
  CELL_NAME:
  CONTAINERIZER_PASSWORD:
  DESIRED_CAPACITY:
  KEY_PAIR:
  NAT_INSTANCE_ID:
  SECURITY_GROUP:
  STACKNAME:
  SUBNET_CIDR:
