groups:
- name: all
  jobs:
  - dolphin-deploy-cf
  - dolphin-destroy-cf
  - baboon-deploy-cf
  - baboon-destroy-cf
  - ferret-deploy-cf
  - ferret-destroy-cf
  - sudbury-deploy-cf
  - sudbury-destroy-cf
  - sudbury-longrunning-test
  - dingo-deploy-cf
  - dingo-destroy-cf
- name: gcp
  jobs:
  - dolphin-deploy-cf
  - dolphin-destroy-cf
  - baboon-deploy-cf
  - baboon-destroy-cf
- name: aws
  jobs:
  - ferret-deploy-cf
  - ferret-destroy-cf
- name: vsphere
  jobs:
  - sudbury-deploy-cf
  - sudbury-destroy-cf
  - sudbury-longrunning-test
- name: azure
  jobs:
  - dingo-deploy-cf
  - dingo-destroy-cf

resources:
- name: cf-deployment
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/cf-deployment.git
    tag_filter: v*
- name: greenhouse-private
  type: git
  source:
    branch: master
    private_key: {{GREENHOUSE_CI_GITHUB_PRIVATE_KEY}}
    uri: git@github.com:pivotal-cf/greenhouse-private
- name: ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry-incubator/greenhouse-ci.git
- name: aws-windows-stemcell
  type: s3
  source:
    bucket: bosh-windows-stemcells-release-candidates
    regexp: light-bosh-stemcell-(.*)-aws-xen-hvm-windows2012R2-go_agent.tgz
- name: gcp-windows-stemcell
  type: s3
  source:
    bucket: bosh-windows-stemcells-release-candidates
    regexp: light-bosh-stemcell-(.*)-google-kvm-windows2012R2-go_agent.tgz
- name: vsphere-windows-stemcell
  type: s3
  source:
    bucket: bosh-windows-stemcells-private-release-candidates
    regexp: bosh-stemcell-(.*)-vsphere-esxi-windows2012R2-go_agent.tgz
    access_key_id: {{BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID}}
    secret_access_key: {{BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY}}
# - name: azure-windows-stemcell
#   type: s3
#   source:
#     bucket: bosh-windows-stemcells-release-candidates
#     regexp: # FILL ME IN
#     access_key_id: {{BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID}}
#     secret_access_key: {{BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY}}
- name: aws-linux-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
- name: gcp-linux-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-google-kvm-ubuntu-trusty-go_agent
- name: vsphere-linux-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-vsphere-esxi-ubuntu-trusty-go_agent
- name: azure-linux-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-azure-hyperv-ubuntu-trusty-go_agent
- name: wats
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/wats.git
- name: cf-smoke-tests
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/cf-smoke-tests.git
- name: weekly-trigger
  type: time
  source:
    days: [Saturday]
    location: US/Eastern
    start: 12:00 AM
    stop: 1:00 AM
- name: hourly-trigger 
  type: time
  source:
    interval: 1h
- name: dolphin-lock-pool
  type: pool
  source:
    branch: master
    pool: dolphin
    private_key: {{GREENHOUSE-CI_SSH_KEY}}
    uri: git@github.com:greenhouse-ci/locks
- name: baboon-lock-pool
  type: pool
  source:
    branch: master
    pool: baboon
    private_key: {{GREENHOUSE-CI_SSH_KEY}}
    uri: git@github.com:greenhouse-ci/locks
- name: ferret-lock-pool
  type: pool
  source:
    branch: master
    pool: ferret
    private_key: {{GREENHOUSE-CI_SSH_KEY}}
    uri: git@github.com:greenhouse-ci/locks
- name: sudbury-lock-pool
  type: pool
  source:
    branch: master
    pool: sudbury
    private_key: {{GREENHOUSE-CI_SSH_KEY}}
    uri: git@github.com:greenhouse-ci/locks
- name: dingo-lock-pool
  type: pool
  source:
    branch: master
    pool: dingo
    private_key: {{GREENHOUSE-CI_SSH_KEY}}
    uri: git@github.com:greenhouse-ci/locks

jobs:
- name: dolphin-destroy-cf
  serial: true
  plan:
  - put: dolphin-lock-pool
    params:
      acquire: true
  - do:
    - aggregate:
      - get: ci
      - get: weekly-trigger
        trigger: true
    - task: destroy-cf
      file: ci/bosh-deld/task.yml
      params:
        BOSH_CLIENT: {{DOLPHIN_BOSH_CLIENT}}
        BOSH_CLIENT_SECRET: {{DOLPHIN_BOSH_CLIENT_SECRET}}
        BOSH_ENVIRONMENT: {{DOLPHIN_BOSH_ENVIRONMENT}}
        BOSH_CA_CERT: {{DOLPHIN_BOSH_CA_CERT}}
    ensure:
      put: dolphin-lock-pool
      params:
        release: dolphin-lock-pool

- name: dolphin-deploy-cf
  serial: true
  plan:
  - put: dolphin-lock-pool
    params:
      acquire: true
  - do:
    - aggregate:
      - get: cf-deployment
      - get: greenhouse-private
      - get: ci
      - get: gcp-windows-stemcell
      - get: gcp-linux-stemcell
      - get: wats
      - get: weekly-trigger
        trigger: true
        passed: [dolphin-destroy-cf]
    - aggregate:
      - task: upload-linux-stemcell
        file: ci/bosh-us/task.yml
        input_mapping: {stemcell: gcp-linux-stemcell}
        params:
          BOSH_CLIENT: {{DOLPHIN_BOSH_CLIENT}}
          BOSH_CLIENT_SECRET: {{DOLPHIN_BOSH_CLIENT_SECRET}}
          BOSH_ENVIRONMENT: {{DOLPHIN_BOSH_ENVIRONMENT}}
          BOSH_CA_CERT: {{DOLPHIN_BOSH_CA_CERT}}
      - task: upload-windows-stemcell
        file: ci/bosh-us/task.yml
        input_mapping: {stemcell: gcp-windows-stemcell}
        params:
          BOSH_CLIENT: {{DOLPHIN_BOSH_CLIENT}}
          BOSH_CLIENT_SECRET: {{DOLPHIN_BOSH_CLIENT_SECRET}}
          BOSH_ENVIRONMENT: {{DOLPHIN_BOSH_ENVIRONMENT}}
          BOSH_CA_CERT: {{DOLPHIN_BOSH_CA_CERT}}
    - task: deploy-cf
      file: ci/deploy-cf/task.yml
      params:
        ENVIRONMENT: dolphin
        BOSH_CLIENT: {{DOLPHIN_BOSH_CLIENT}}
        BOSH_CLIENT_SECRET: {{DOLPHIN_BOSH_CLIENT_SECRET}}
        BOSH_ENVIRONMENT: {{DOLPHIN_BOSH_ENVIRONMENT}}
        BOSH_CA_CERT: {{DOLPHIN_BOSH_CA_CERT}}
        CF_DOMAIN: dolphin.cf-app.com
    - put: greenhouse-private
      params:
        repository: output/greenhouse-private
        rebase: true
    - task: clean-up
      file: ci/bosh-cleanup/task.yml
      params:
        BOSH_CLIENT: {{DOLPHIN_BOSH_CLIENT}}
        BOSH_CLIENT_SECRET: {{DOLPHIN_BOSH_CLIENT_SECRET}}
        BOSH_ENVIRONMENT: {{DOLPHIN_BOSH_ENVIRONMENT}}
        BOSH_CA_CERT: {{DOLPHIN_BOSH_CA_CERT}}
    - task: wats
      file: ci/run-wats/task.yml
      params:
        ADMIN_PASSWORD: {{DOLPHIN_ADMIN_PASSWORD}}
        ADMIN_USER: admin
        API: api.dolphin.cf-app.com
        APPS_DOMAIN: dolphin.cf-app.com
        NUM_WIN_CELLS: 1
        SOCKET_ADDRESS_FOR_SECURITY_GROUP_TEST: 10.0.0.6:25555
    ensure:
      put: dolphin-lock-pool
      params:
        release: dolphin-lock-pool

- name: baboon-destroy-cf
  serial: true
  plan:
  - put: baboon-lock-pool
    params:
      acquire: true
  - do:
    - aggregate:
      - get: ci
      - get: weekly-trigger
        trigger: true
    - task: destroy-cf
      file: ci/bosh-deld/task.yml
      params:
        BOSH_CLIENT: {{BABOON_BOSH_CLIENT}}
        BOSH_CLIENT_SECRET: {{BABOON_BOSH_CLIENT_SECRET}}
        BOSH_ENVIRONMENT: {{BABOON_BOSH_ENVIRONMENT}}
        BOSH_CA_CERT: {{BABOON_BOSH_CA_CERT}}
    ensure:
      put: baboon-lock-pool
      params:
        release: baboon-lock-pool

- name: baboon-deploy-cf
  serial: true
  plan:
  - put: baboon-lock-pool
    params:
      acquire: true
  - do:
    - aggregate:
      - get: cf-deployment
      - get: greenhouse-private
      - get: ci
      - get: gcp-windows-stemcell
      - get: gcp-linux-stemcell
      - get: wats
      - get: weekly-trigger
        trigger: true
        passed: [baboon-destroy-cf]
    - aggregate:
      - task: upload-linux-stemcell
        file: ci/bosh-us/task.yml
        input_mapping: {stemcell: gcp-linux-stemcell}
        params:
          BOSH_CLIENT: {{BABOON_BOSH_CLIENT}}
          BOSH_CLIENT_SECRET: {{BABOON_BOSH_CLIENT_SECRET}}
          BOSH_ENVIRONMENT: {{BABOON_BOSH_ENVIRONMENT}}
          BOSH_CA_CERT: {{BABOON_BOSH_CA_CERT}}
      - task: upload-windows-stemcell
        file: ci/bosh-us/task.yml
        input_mapping: {stemcell: gcp-windows-stemcell}
        params:
          BOSH_CLIENT: {{BABOON_BOSH_CLIENT}}
          BOSH_CLIENT_SECRET: {{BABOON_BOSH_CLIENT_SECRET}}
          BOSH_ENVIRONMENT: {{BABOON_BOSH_ENVIRONMENT}}
          BOSH_CA_CERT: {{BABOON_BOSH_CA_CERT}}
    - task: deploy-cf
      file: ci/deploy-cf/task.yml
      params:
        ENVIRONMENT: baboon
        BOSH_CLIENT: {{BABOON_BOSH_CLIENT}}
        BOSH_CLIENT_SECRET: {{BABOON_BOSH_CLIENT_SECRET}}
        BOSH_ENVIRONMENT: {{BABOON_BOSH_ENVIRONMENT}}
        BOSH_CA_CERT: {{BABOON_BOSH_CA_CERT}}
        CF_DOMAIN: baboon.cf-app.com
    - put: greenhouse-private
      params:
        repository: output/greenhouse-private
        rebase: true
    - task: clean-up
      file: ci/bosh-cleanup/task.yml
      params:
        BOSH_CLIENT: {{BABOON_BOSH_CLIENT}}
        BOSH_CLIENT_SECRET: {{BABOON_BOSH_CLIENT_SECRET}}
        BOSH_ENVIRONMENT: {{BABOON_BOSH_ENVIRONMENT}}
        BOSH_CA_CERT: {{BABOON_BOSH_CA_CERT}}
    - task: wats
      file: ci/run-wats/task.yml
      params:
        ADMIN_PASSWORD: {{BABOON_ADMIN_PASSWORD}}
        ADMIN_USER: admin
        API: api.baboon.cf-app.com
        APPS_DOMAIN: baboon.cf-app.com
        NUM_WIN_CELLS: 1
        SOCKET_ADDRESS_FOR_SECURITY_GROUP_TEST: 10.0.0.6:25555
    ensure:
      put: baboon-lock-pool
      params:
        release: baboon-lock-pool

- name: ferret-destroy-cf
  serial: true
  plan:
  - put: ferret-lock-pool
    params:
      acquire: true
  - do:
    - aggregate:
      - get: ci
      - get: weekly-trigger
        trigger: true
    - task: destroy-cf
      file: ci/bosh-deld/task.yml
      params:
        BOSH_CLIENT: {{FERRET_BOSH_CLIENT}}
        BOSH_CLIENT_SECRET: {{FERRET_BOSH_CLIENT_SECRET}}
        BOSH_ENVIRONMENT: {{FERRET_BOSH_ENVIRONMENT}}
        BOSH_CA_CERT: {{FERRET_BOSH_CA_CERT}}
    ensure:
      put: ferret-lock-pool
      params:
        release: ferret-lock-pool

- name: ferret-deploy-cf
  serial: true
  plan:
  - put: ferret-lock-pool
    params:
      acquire: true
  - do:
    - aggregate:
      - get: cf-deployment
      - get: greenhouse-private
      - get: ci
      - get: aws-windows-stemcell
      - get: aws-linux-stemcell
      - get: wats
      - get: weekly-trigger
        trigger: true
        passed: [ferret-destroy-cf]
    - aggregate:
      - task: upload-linux-stemcell
        file: ci/bosh-us/task.yml
        input_mapping: {stemcell: aws-linux-stemcell}
        params:
          BOSH_CLIENT: {{FERRET_BOSH_CLIENT}}
          BOSH_CLIENT_SECRET: {{FERRET_BOSH_CLIENT_SECRET}}
          BOSH_ENVIRONMENT: {{FERRET_BOSH_ENVIRONMENT}}
          BOSH_CA_CERT: {{FERRET_BOSH_CA_CERT}}
      - task: upload-windows-stemcell
        file: ci/bosh-us/task.yml
        input_mapping: {stemcell: aws-windows-stemcell}
        params:
          BOSH_CLIENT: {{FERRET_BOSH_CLIENT}}
          BOSH_CLIENT_SECRET: {{FERRET_BOSH_CLIENT_SECRET}}
          BOSH_ENVIRONMENT: {{FERRET_BOSH_ENVIRONMENT}}
          BOSH_CA_CERT: {{FERRET_BOSH_CA_CERT}}
    - task: deploy-cf
      file: ci/deploy-cf/task.yml
      params:
        ENVIRONMENT: ferret
        BOSH_CLIENT: {{FERRET_BOSH_CLIENT}}
        BOSH_CLIENT_SECRET: {{FERRET_BOSH_CLIENT_SECRET}}
        BOSH_ENVIRONMENT: {{FERRET_BOSH_ENVIRONMENT}}
        BOSH_CA_CERT: {{FERRET_BOSH_CA_CERT}}
        CF_DOMAIN: greenhouse-ferret.cf-app.com
    - put: greenhouse-private
      params:
        repository: output/greenhouse-private
        rebase: true
    - task: clean-up
      file: ci/bosh-cleanup/task.yml
      params:
        BOSH_CLIENT: {{FERRET_BOSH_CLIENT}}
        BOSH_CLIENT_SECRET: {{FERRET_BOSH_CLIENT_SECRET}}
        BOSH_ENVIRONMENT: {{FERRET_BOSH_ENVIRONMENT}}
        BOSH_CA_CERT: {{FERRET_BOSH_CA_CERT}}
    - task: wats
      file: ci/run-wats/task.yml
      params:
        ADMIN_PASSWORD: {{FERRET_ADMIN_PASSWORD}}
        ADMIN_USER: admin
        API: api.greenhouse-ferret.cf-app.com
        APPS_DOMAIN: greenhouse-ferret.cf-app.com
        NUM_WIN_CELLS: 1
        SOCKET_ADDRESS_FOR_SECURITY_GROUP_TEST: 10.0.0.6:25555
    ensure:
      put: ferret-lock-pool
      params:
        release: ferret-lock-pool

- name: sudbury-destroy-cf
  serial: true
  plan:
  - put: sudbury-lock-pool
    params:
      acquire: true
  - do:
    - aggregate:
      - get: ci
      - get: weekly-trigger
        trigger: true
    - task: destroy-cf
      file: ci/bosh-deld/task.yml
      tags: [vsphere]
      params:
        BOSH_CLIENT: admin
        BOSH_CLIENT_SECRET: {{sudbury_client_secret}}
        BOSH_ENVIRONMENT: {{sudbury_environment}}
        BOSH_CA_CERT: {{sudbury_ca_cert}}
    ensure:
      put: sudbury-lock-pool
      params:
        release: sudbury-lock-pool

- name: sudbury-deploy-cf
  serial: true
  plan:
  - put: sudbury-lock-pool
    params:
      acquire: true
  - do:
    - aggregate:
      - get: cf-deployment
      - get: greenhouse-private
      - get: ci
      - get: vsphere-windows-stemcell
        tags: [vsphere]
      - get: vsphere-linux-stemcell
        tags: [vsphere]
      - get: wats
      - get: weekly-trigger
        trigger: true
        passed: [sudbury-destroy-cf]
    - aggregate:
      - task: upload-linux-stemcell
        file: ci/bosh-us/task.yml
        input_mapping: {stemcell: vsphere-linux-stemcell}
        tags: [vsphere]
        params:
          BOSH_CLIENT: admin
          BOSH_CLIENT_SECRET: {{sudbury_client_secret}}
          BOSH_ENVIRONMENT: {{sudbury_environment}}
          BOSH_CA_CERT: {{sudbury_ca_cert}}
      - task: upload-windows-stemcell
        file: ci/bosh-us/task.yml
        input_mapping: {stemcell: vsphere-windows-stemcell}
        tags: [vsphere]
        params:
          BOSH_CLIENT: admin
          BOSH_CLIENT_SECRET: {{sudbury_client_secret}}
          BOSH_ENVIRONMENT: {{sudbury_environment}}
          BOSH_CA_CERT: {{sudbury_ca_cert}}
    - task: deploy-cf
      tags: [vsphere]
      file: ci/deploy-cf/task.yml
      params:
        ENVIRONMENT: sudbury
        BOSH_CLIENT: admin
        BOSH_CLIENT_SECRET: {{sudbury_client_secret}}
        BOSH_ENVIRONMENT: {{sudbury_environment}}
        BOSH_CA_CERT: {{sudbury_ca_cert}}
        CF_DOMAIN: sudbury.cf-app.com
    - put: greenhouse-private
      params:
        repository: output/greenhouse-private
        rebase: true
    - task: clean-up
      file: ci/bosh-cleanup/task.yml
      tags: [vsphere]
      params:
        BOSH_CLIENT: admin
        BOSH_CLIENT_SECRET: {{sudbury_client_secret}}
        BOSH_ENVIRONMENT: {{sudbury_environment}}
        BOSH_CA_CERT: {{sudbury_ca_cert}}
    - task: wats
      tags: [vsphere]
      file: ci/run-wats/task.yml
      params:
        ADMIN_PASSWORD: {{sudbury_cf_admin_password}}
        ADMIN_USER: admin
        API: api.sudbury.cf-app.com
        APPS_DOMAIN: sudbury.cf-app.com
        NUM_WIN_CELLS: 1
        SOCKET_ADDRESS_FOR_SECURITY_GROUP_TEST: 10.74.41.6:25555
    ensure:
      put: sudbury-lock-pool
      params:
        release: sudbury-lock-pool

- name: dingo-destroy-cf
  serial: true
  plan:
  - put: dingo-lock-pool
    params:
      acquire: true
  - do:
    - aggregate:
      - get: ci
      - get: weekly-trigger
        trigger: true
    - task: destroy-cf
      file: ci/bosh-deld/task.yml
      params:
        BOSH_CLIENT: admin
        BOSH_CLIENT_SECRET: {{dingo_client_secret}}
        BOSH_ENVIRONMENT: {{dingo_environment}}
        BOSH_CA_CERT: {{dingo_ca_cert}}
    ensure:
      put: dingo-lock-pool
      params:
        release: dingo-lock-pool

- name: dingo-deploy-cf
  serial: true
  plan:
  - put: dingo-lock-pool
    params:
      acquire: true
  - do:
    - aggregate:
      - get: cf-deployment
      - get: greenhouse-private
      - get: ci
      # - get: azure-windows-stemcell
      - get: azure-linux-stemcell
      - get: wats
      - get: weekly-trigger
        trigger: true
        passed: [dingo-destroy-cf]
    - aggregate:
      - task: upload-linux-stemcell
        file: ci/bosh-us/task.yml
        input_mapping: {stemcell: azure-linux-stemcell}
        params:
          BOSH_CLIENT: admin
          BOSH_CLIENT_SECRET: {{dingo_client_secret}}
          BOSH_ENVIRONMENT: {{dingo_environment}}
          BOSH_CA_CERT: {{dingo_ca_cert}}
      # - task: upload-windows-stemcell
      #   file: ci/bosh-us/task.yml
      #   input_mapping: {stemcell: azure-windows-stemcell}
      #   params:
      #     BOSH_CLIENT: admin
      #     BOSH_CLIENT_SECRET: {{dingo_client_secret}}
      #     BOSH_ENVIRONMENT: {{dingo_environment}}
      #     BOSH_CA_CERT: {{dingo_ca_cert}}
    - task: deploy-cf
      file: ci/deploy-cf/task.yml
      params:
        ENVIRONMENT: dingo
        BOSH_CLIENT: admin
        BOSH_CLIENT_SECRET: {{dingo_client_secret}}
        BOSH_ENVIRONMENT: {{dingo_environment}}
        BOSH_CA_CERT: {{dingo_ca_cert}}
        CF_DOMAIN: dingo.cf-app.com
    - put: greenhouse-private
      params:
        repository: output/greenhouse-private
        rebase: true
    - task: clean-up
      file: ci/bosh-cleanup/task.yml
      params:
        BOSH_CLIENT: admin
        BOSH_CLIENT_SECRET: {{dingo_client_secret}}
        BOSH_ENVIRONMENT: {{dingo_environment}}
        BOSH_CA_CERT: {{dingo_ca_cert}}
    - task: wats
      file: ci/run-wats/task.yml
      params:
        ADMIN_PASSWORD: {{dingo_cf_admin_password}}
        ADMIN_USER: admin
        API: api.dingo.cf-app.com
        APPS_DOMAIN: dingo.cf-app.com
        NUM_WIN_CELLS: 1
        SOCKET_ADDRESS_FOR_SECURITY_GROUP_TEST: 10.0.0.6:25555
    ensure:
      put: dingo-lock-pool
      params:
        release: dingo-lock-pool

- name: sudbury-longrunning-test
  plan:
  - aggregate:
    - get: hourly-trigger
      trigger: true
    - get: ci
    - get: cf-smoke-tests
  - task: run
    tags: [vsphere]
    file: ci/longrunning/task.yml
    params:
      DOMAIN: sudbury.cf-app.com
      ADMIN_PASSWORD: {{sudbury_cf_admin_password}}
