---
platform: linux
image_resource: { type: docker-image, source: {repository: pivotalgreenhouse/govc } }

inputs:
  - name: ci

run:
  path: ci/tasks/revert-snapshot/run.sh

params:
  GOVC_URL:
  DATACENTER:
  VM_TO_REVERT:
  VM_CUSTOMIZATION_NAME: Bosh-Windows-Base
  SNAPSHOT_NAME:
