---
platform: linux
image_resource: { type: docker-image, source: {repository: pivotalgreenhouse/ci } }
inputs:
- name: stemcell-builder
- name: bosh-agent-release
outputs:
- name: bosh-agent
run:
  path: bash
  args:
  - "-c"
  - "cd stemcell-builder && bundle && rake package:agent && mv build/*.zip ../bosh-agent"
