---
platform: linux
image_resource: { type: docker-image, source: {repository: pivotalgreenhouse/ci } }
inputs:
- name: main-version
outputs:
- name: stemcell-builder-release-version
run:
  path: bash
  args:
  - "-c"
  - "cat stemcells-main-version/version | sed -e 's#\\([0-9]*\\.[0-9]*\\)\\.[0-9]*#\\1#' > stemcell-builder-release-version/version"
